spring:
  cloud:
    stream:
      function:
        definition: orderSupplier;paymentEventCosumer
      bindings:
        order-supplier-out-0:
          destination: order-event
        paymentEventCosumer-in-0:
          destination: payment-event
server:
  port: 8081